### ISSUE TITLE
Missings

### ISSUE THREAD

**Issue by KarolineHuth** [MaartenMarsman/bgms#10]
If missings included in the data: 
Error in if (no_categories[node] == 0) stop(paste0("Only one value [",  : 
  missing value where TRUE/FALSE needed

Suggestion 1: change to informative error. check for missings in the beginning and give an informative error

Suggestion 2: check for missings in the beginning, delete listwise, and give a warning that missings were in the data and were deleted listwise

**Comment by MaartenMarsman** [comment]
With commit #[3299179](https://github.com/MaartenMarsman/bgms/commit/3299179302147a0ab5deea91194e5e6afd98cf6c), I followed your Suggestion 2.
