### ISSUE TITLE
Error in bgm using matrix for inclusion_probability

### ISSUE THREAD

**Issue by martinobelvederi** [MaartenMarsman/bgms#21]
Hello and congratulations for the really nice package!
second time I post an issue, so hope to do it right.
I'm trying to provide a matrix of inclusion probabilities for each edge in the bernoulli model. Despite providing a matrix with or without col/rownames, I receive an error "The input for the inclusion probability argument needs to be a single number, matrix, or dataframe."

here is what I hope is a reproducible example
thanks a lot in advance! Martino

set.seed(123) # For reproducibility
db1_sample <- matrix(sample(0:1, 600, replace = TRUE), nrow=50, ncol=12)
mat1_sample <- matrix(runif(min = 0, max = 1, n = 144), ncol = 12)
diag(mat1_sample) <- 1
mat1_sample[upper.tri(mat1_sample)] <- t(mat1_sample)[upper.tri(mat1_sample)]
isSymmetric(mat1_sample)

#Reproduce the issue
net.bern2 <- bgm(x = as.matrix(db1_sample),
inclusion_probability = mat1_sample)

net.bern2 <- bgm(x = db1_sample, inclusion_probability = mat1_sample)

Error in bgm(x = as.matrix(db1_sample), inclusion_probability = mat1_sample) :
The input for the inclusion probability argument needs to be a single number, matrix, or dataframe.

**Comment by MaartenMarsman** [comment]
Hi Martino, 

Thanks for catching this! I checked the code for the background music and apparently made a mistake in checking the inclusion probability matrix. I have fixed the bug. 

You can download the updated version of the bgms with the following code. 

if (!requireNamespace("remotes")) { 
  install.packages("remotes")   
}   
remotes::install_github("MaartenMarsman/bgms")

Can you confirm that it works as expected now? 

Best,
Maarten

**Comment by martinobelvederi** [comment]
it worked! thanks a lot for the amazing work!
