### ISSUE TITLE
FR: reduce object size

### ISSUE THREAD

**Issue by vandenman** [MaartenMarsman/bgms#22]
For the Dense vs Sparse, the main object size of `rowSums(fit$gamma)` comes from the names of `fit$gamma`. I can reduce the size by a factor 4 (from 40MB to 10 MB) by removing the names altogether!

You could remove the rownames entirely, but if you prefer to keep the "Iter." you could change these lines

https://github.com/MaartenMarsman/bgms/blob/f5b40843becaf4bb074b5916ebc1c047cf01d5e0/R/bgm.R#L497-L499

to
```r
dimnames(gamma)  <- list(Iter. = 1:nrow(gamma), colnames(gamma))
dimnames(interactions)  <- list(Iter. = 1:nrow(interactions), colnames(interactions))
dimnames(thresholds)  <- list(Iter. = 1:nrow(thresholds), colnames(thresholds))
```
and then `fit$gamma` will be printed like so:
```r
> gamma[, 1:3]

Iter. dreams-intrusion flash-intrusion upset-intrusion
   1                 1               1               1
   2                 1               1               1
   3                 1               1               1
   4                 1               1               1
   5                 1               1               1
   6                 1               1               1
   7                 1               1               1
   8                 1               1               1
   9                 1               1               1
   10                1               1               1
```
This is much more space-efficient since integers are smaller than strings. Also, this primarily affects the situation where `save = TRUE`.

**Comment by MaartenMarsman** [comment]
Closed with commit 93e4888
