### ISSUE TITLE
edge prior argument specification if edge_selection = F

### ISSUE THREAD

**Issue by KarolineHuth** [MaartenMarsman/bgms#24]
<img width="443" alt="Screenshot 2024-02-19 at 10 16 30 PM" src="https://github.com/MaartenMarsman/bgms/assets/55590854/f139ed9b-95d7-4a33-be8b-313c38311a7f">

**Comment by MaartenMarsman** [comment]
This is now fixed as follows:

<img width="181" alt="Screenshot 2024-02-21 at 13 12 30" src="https://github.com/MaartenMarsman/bgms/assets/52934067/cfda994c-87c9-402b-8595-9cd357eeadb2">
