### ISSUE TITLE
FR: Use column names of x as labels for nodes in output and only if empty use node 1 to node p as labels in output

### ISSUE THREAD

**Issue by KarolineHuth** [MaartenMarsman/bgms#8]

**Comment by MaartenMarsman** [comment]
Resolved with Commits #[4049c2b] (https://github.com/MaartenMarsman/bgms/commit/4049c2ba327c136bb723216d9016d37cd6dbe0bb) and #[fa6cbe6](https://github.com/MaartenMarsman/bgms/commit/fa6cbe6369c3c78e527992f64dc21391db1f9ab8)
