### ISSUE TITLE
FR: Include summary() and plot() argument

### ISSUE THREAD

**Issue by KarolineHuth** [MaartenMarsman/bgms#9]

**Comment by MaartenMarsman** [comment]
I included a print statement. For summary and plotting I explicitly suggest using easybgm in the print statement:
<img width="555" alt="Screenshot 2024-02-21 at 13 15 18" src="https://github.com/MaartenMarsman/bgms/assets/52934067/608ed081-a3bd-47f8-a9a8-af24aa63c8fd">
